defmodule NexusRealtimeServerWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :nexus_realtime_server

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_nexus_realtime_server_key",
    signing_salt: "5UlWl+5l",
    same_site: "Lax"
  ]



   # --- HTTP CORS ---
   # 1. HTTP CORS (Standard function capture)
  plug CORSPlug,
    origin: &NexusRealtimeServerWeb.Endpoint.get_cors_origins/1,
    credentials: true

  # 2. WebSocket (MFA Tuple)
  socket "/realtime", NexusRealtimeServerWeb.RealtimeSocket,
    websocket: [
      connect_info: [:peer_data],
      check_origin: {__MODULE__, :get_ws_origins_mfa, []}
    ],
    longpoll: false

  # --- Helpers ---

  # Used by CORSPlug (receives %Plug.Conn{})
  def get_cors_origins(_conn) do
    Application.get_env(:nexus_realtime_server, :cors_origins, ["http://localhost:3000"])
  end

  # Used by Socket (receives %URI{} as first argument)
  # Change this to accept 1 argument
  def get_ws_origins_mfa(_uri) do
    Application.get_env(:nexus_realtime_server, :websocket_origins, ["http://localhost:3000"])
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :nexus_realtime_server,
    gzip: not code_reloading?,
    only: NexusRealtimeServerWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :nexus_realtime_server
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug NexusRealtimeServerWeb.Router
end
